name: Aravis-MSVC

on:
  push:
    branches:
      - 'feature/8-build-aravis-in-workflow'
  # Uncomment below if you want to trigger the workflow on pull requests
  # pull_request:
  #   branches:
  #     - '*'
  workflow_dispatch:

jobs:
  aravis_msvc:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 16
            arch: x86_64
            build_type_conan: Release
            build_type_meson: release
            aravis_version: "0.8.25"

    steps:
      - name: Install Conan
        run: |
          pip install "conan==1.57.0"

      - name: Disable Perl
        run: |
          choco uninstall mingw strawberryperl
          refreshenv

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone and checkout specific tag of Aravis
        run: |
          git clone https://github.com/AravisProject/aravis.git installer/aravis
          cd installer/aravis
          git checkout "${{ matrix.aravis_version }}"

      - name: Setup Conan Dependencies
        working-directory: installer/aravis
        env:
          INPUT_CONANFILE: |
            [requires]
            libiconv/1.17
            gstreamer/1.22.3
            libxml2/2.10.3
            zlib/1.2.13
            libusb/1.0.26

            [build_requires]
            meson/0.59.2
            pkgconf/1.9.3

            [generators]
            pkg_config
            virtualenv
            virtualbuildenv
            virtualrunenv

            [options]
            glib:shared=True
            gstreamer:shared=True
            gst-plugins-base:shared=True
        run: |
          $Env:INPUT_CONANFILE | Out-File -FilePath ${{ github.workspace }}\installer\aravis\conanfile.txt -Encoding utf8
          conan install `
            -s os="Windows" `
            -s compiler="Visual Studio" `
            -s compiler.version=${{ matrix.version }} `
            -s arch=${{ matrix.arch }} `
            -s build_type=${{ matrix.build_type_conan }} `
            -b missing `
            -b cascade `
            -if build .

      - name: Setup MSVC Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Build with Meson
        working-directory: installer/aravis
        run: |
          .\build\activate.ps1
          .\build\activate_build.ps1
          .\build\activate_run.ps1

          echo "::group::configure"
          meson `
            --prefix ${{ github.workspace }}\install `
            --buildtype ${{ matrix.build_type_meson }} `
            --pkg-config-path ${{ github.workspace }}\build `
            -Ddocumentation=disabled `
            -Dgst-plugin=disabled `
            -Dintrospection=disabled `
            -Dusb=enabled `
            -Dviewer=disabled `
            -Dgv-n-buffers=1 `
            . .\build
          echo "::endgroup::"

          echo "::group::compile"
          meson compile -C .\build -v
          echo "::endgroup::"

          echo "::group::install"
          meson install -C .\build
          echo "::endgroup::"

      - name: Test
        working-directory: installer/aravis
        run: |
          .\build\activate.ps1
          .\build\activate_build.ps1
          .\build\activate_run.ps1
          meson test -C .\build

      - name: Upload Logs on Failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: msvc_${{ matrix.version }}_${{ matrix.arch }}_${{ matrix.build_type_meson }}_Meson_Testlog
          path: build/meson-logs/testlog.txt
