name: Sensing dev installer Build and Release

on:
  push:
    tags:
      - "v*.*.*"  # vYY.MM.Patch example v23.08.00 etc.

jobs:
  release:
    runs-on: windows-latest
    
    steps:
      - name: Set up Python and Install Conan via pip
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.4"
      - run: python -m pip install conan
      - run: python -m pip install PyYAML

      - name: Disable Perl (remove from PATH)
        run: choco uninstall mingw strawberryperl

      - name: Install WiX Toolset
        run: choco install wixtoolset -y

      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create and enter build directory
        run: |
          cd installer
          mkdir build
          cd build

      - name: Run CMake
        working-directory: installer/build
        run: cmake -G "Visual Studio 17 2022" -A x64 ../

      - name: Build
        working-directory: installer/build
        run: cmake --build . --config Release 

      - name: Create package msi
        working-directory: installer/build
        run: cpack -G "WIX"

      - name: Create package zip
        working-directory: installer/build
        run: cpack -G "ZIP"

      - name: Release      
        uses: softprops/action-gh-release@v1
        with:
          files: |
            installer/build/*.msi
            installer/build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create GitHub Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: Sensing dev installer msi.
      #     draft: false
      #     prerelease: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload Release Asset (MSI)
      #   uses: actions/upload-release-asset@v1
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./installer/build/sensing-dev-installer.msi  
      #     asset_name: sensing-dev-installer.msi
      #     asset_content_type: application/x-msi
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      





