# setup-environment.yml

inputs:
  python-version:
    description: 'Python version to setup'
    required: true
    default: '3.11.4'

runs:
  using: "composite"
  steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: ${{ inputs.python-version }}
  - name: Install Conan via pip
    run: python -m pip install conan
    shell: bash
  - name: Setup MSVC Developer Command Prompt
    uses: TheMrMilchmann/setup-msvc-dev@v3
    with:
      arch: x64
