libraries:
  aravis:
    name: aravis
    src_path: aravis
    install_path: install/aravis
    action: build # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://ion-kit.s3.us-west-2.amazonaws.com/dependencies/Aravis-0.8.25.zip"
    pkg_sha: "f18462e10006c05779854ebf59f97906762d70b2fc90225669ec7e140969adb3"
    git_repo: "https://github.com/AravisProject/aravis.git"
    version: "0.8.25"

  pygobject:
    name: pygobject
    src_path: pygobject
    install_path: install/pygobject
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://ion-kit.s3.us-west-2.amazonaws.com/dependencies/pygobject-3.42.2.zip"
    pkg_sha: "eea9465b7cbf1420ee3b3d8a78f6cfa3feeff89ffade7ab1874ebb25d7078037"
    git_repo: "https://gitlab.gnome.org/GNOME/pygobject.git"
    version: "3.42.2"

  ion_kit:
    name: ion-kit
    src_path: ion-kit
    install_path: install/ion-kit
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://github.com/fixstars/ion-kit/releases/download/v0.3.4/ion-kit-0.3.4-win64.zip"
    pkg_sha: "3d6edc0ad63f07e54a9d5c10d672b1e48154aa4deb374eb5ecc66d40bcef32b1"
    git_repo: "https://github.com/fixstars/ion-kit.git"
    version: "0.3.4"

  opencv:
    name: opencv
    src_path: opencv
    install_path: install/opencv
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://github.com/opencv/opencv/releases/download/4.5.5/opencv-4.5.5-vc14_vc15.exe"
    pkg_sha: "cac31973cd1c59bfe9dc926acbde815553d23662ea355e0414b5e50d8f8aa5a8"
    version: "4.5.5"
