libraries:
  aravis:
    name: aravis
    src_path: aravis
    install_path: install/aravis
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://github.com/Sensing-Dev/aravis/releases/download/v0.8.30-internal.1/aravis-0.8.30-internal.1-x86-64-windows.zip"
    pkg_sha: "b78cc27c9e8b65b2eafdb27a4fd7140690b8afe1ee4bb0b8864194b470373539"
    git_repo: "https://github.com/Sensing-Dev/aravis.git"
    version: "v0.8.30-internal.1"

  aravis_dep:
    name: aravis_dep
    src_path: aravis_dep
    install_path: install/aravis_dep
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://github.com/Sensing-Dev/aravis/releases/download/v0.8.30-internal.1/aravis-0.8.30-internal.1-dependencies_update.zip"
    pkg_sha: "a016fbdbcd1641471e3b222473c8cdac514092788656c7ff90cfd14e3ee1b059"
    git_repo: "https://github.com/conan-io/conan-center-index.git" # use recipe here for appropriate version
    version: "v0.8.30-internal.1"

  pygobject:
    name: pygobject
    src_path: pygobject
    install_path: install/pygobject
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://ion-kit.s3.us-west-2.amazonaws.com/dependencies/pygobject-3.42.2.zip"
    pkg_sha: "eea9465b7cbf1420ee3b3d8a78f6cfa3feeff89ffade7ab1874ebb25d7078037"
    git_repo: "https://gitlab.gnome.org/GNOME/pygobject.git"
    version: "3.42.2"

  ion_kit:
    name: ion-kit
    src_path: ion-kit
    install_path: install/ion-kit
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://github.com/fixstars/ion-kit/releases/download/v1.8.10/ion-kit-1.8.10-x86-64-windows.zip"
    pkg_sha: "91aa157baafec5ef44e09d25f0fee7a982495c4e83f6b16913673a55ccbf83a8"
    git_repo: "https://github.com/fixstars/ion-kit.git"
    version: "v1.8.10"

  opencv:
    name: opencv
    src_path: opencv
    install_path: install/opencv
    # action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://github.com/opencv/opencv/releases/download/4.5.5/opencv-4.5.5-vc14_vc15.exe"
    pkg_sha: "cac31973cd1c59bfe9dc926acbde815553d23662ea355e0414b5e50d8f8aa5a8"
    version: "4.5.5"

  gendc_separator:
    name: gendc_separator
    src_path: gendc_separator
    install_path: install/gendc_separator
    # action: download # can be 'download'
    pkg_url: "https://github.com/Sensing-Dev/GenDC/releases/download/v0.2.8/gendc_separator_v0.2.8_win64.zip"
    pkg_sha: "bdcf560332bf90dc07ebd50d931f86003fc8cbd54336009e03828d8aa45f965d"
    git_repo: "https://github.com/Sensing-Dev/GenDC.git"
    version: "v0.2.8"


