libraries:
  aravis:
    name: aravis
    src_path: aravis
    install_path: install/aravis
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://github.com/Sensing-Dev/aravis/releases/download/internal-0.8.30/aravis-internal-0.8.30-win64.zip"
    pkg_sha: "a328e603e8bef843f3824f0d04e5d6b754ee9a82d4c388044d48ae4cd35f89a8"
    git_repo: "https://github.com/Sensing-Dev/aravis.git"
    version: "0.8.30-internal"

  aravis_dep:
    name: aravis_dep
    src_path: aravis_dep
    install_path: install/aravis_dep
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://github.com/Sensing-Dev/aravis/releases/download/internal-0.8.30/Aravis-0.8.30-internal-dependencies.zip"
    pkg_sha: "f1f93b6c8ee2dd881e7c8950b06562159fb55f615d7ae2de165d861194e9b6c3"
    git_repo: "https://github.com/conan-io/conan-center-index.git" # use recipe here for appropriate version
    version: "0.8.30-internal"

  pygobject:
    name: pygobject
    src_path: pygobject
    install_path: install/pygobject
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://ion-kit.s3.us-west-2.amazonaws.com/dependencies/pygobject-3.42.2.zip"
    pkg_sha: "eea9465b7cbf1420ee3b3d8a78f6cfa3feeff89ffade7ab1874ebb25d7078037"
    git_repo: "https://gitlab.gnome.org/GNOME/pygobject.git"
    version: "3.42.2"

  ion_kit:
    name: ion-kit
    src_path: ion-kit
    install_path: install/ion-kit
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://github.com/fixstars/ion-kit/releases/download/v1.0.0/ion-kit-1.0.0-x86-64-windows.zip"
    pkg_sha: "e5e32c7340777ad9dbeea52daa99f569db597b7ab0f3a10f932f04de28df5ec7"
    git_repo: "https://github.com/fixstars/ion-kit.git"
    version: "v1.0.0"

  opencv:
    name: opencv
    src_path: opencv
    install_path: install/opencv
    # action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://github.com/opencv/opencv/releases/download/4.5.5/opencv-4.5.5-vc14_vc15.exe"
    pkg_sha: "cac31973cd1c59bfe9dc926acbde815553d23662ea355e0414b5e50d8f8aa5a8"
    version: "4.5.5"
