libraries:
  aravis:
    name: aravis
    src_path: aravis # All paths are relative to CMAKE_SOURCE_DIR
    install_path: dependencies/aravis
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://ion-kit.s3.us-west-2.amazonaws.com/dependencies/Aravis-0.8.25-patched-0fec828.zip"
    pkg_sha: "233bcac1f50fbd2aea6f9572171a77e0655386709a7813ef993b05e3168c6e8f"
    git_repo: "https://github.com/AravisProject/aravis.git"
    version: "0.8.25"

  aravis_dep:
    name: aravis-dependencies
    src_path: aravis_dep
    install_path: dependencies/aravis_dependencies
    action: build # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://ion-kit.s3.us-west-2.amazonaws.com/dependencies/Aravis-dependencies.zip"
    pkg_sha: "c0b26fc0c0d2fde51f13107b450c66808ee88d15c2adb0a1f6d4b473f282c3a9"
    git_repo: ""
    version: ""

  pygobject:
    name: pygobject
    src_path: pygobject
    install_path: dependencies/pygobject
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://ion-kit.s3.us-west-2.amazonaws.com/dependencies/pygobject-3.42.2.zip"
    pkg_sha: "eea9465b7cbf1420ee3b3d8a78f6cfa3feeff89ffade7ab1874ebb25d7078037"
    git_repo: "https://gitlab.gnome.org/GNOME/pygobject.git"
    version: "3.42.2"

  ion_kit:
    name: ion-kit
    src_path: ion-kit
    install_path: dependencies/ion-kit
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://github.com/fixstars/ion-kit/releases/download/v0.3.5/ion-kit-0.3.5-win64.zip"
    pkg_sha: "93ddfeb8ba3aeb02caeb9bd6668527c1ea4b4305172695766f348fe5e7455a5c"
    git_repo: "https://github.com/fixstars/ion-kit.git"
    version: "0.3.5"

  opencv:
    name: opencv
    src_path: opencv
    install_path: dependencies/opencv
    action: download # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://github.com/opencv/opencv/releases/download/4.5.5/opencv-4.5.5-vc14_vc15.exe"
    pkg_sha: "cac31973cd1c59bfe9dc926acbde815553d23662ea355e0414b5e50d8f8aa5a8"
    git_repo: ""
    version: "4.5.5"
